# Generated by Django 2.1 on 2018-08-15 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': '类别',
                'db_table': '类别',
                'verbose_name': '类别',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='category')),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('Modtime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
            options={
                'ordering': ('Createtime',),
                'verbose_name_plural': '项目列表',
                'db_table': '项目列表',
                'verbose_name': '项目列表',
            },
        ),
    ]
