# Generated by Django 2.0.7 on 2018-11-13 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adl_borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('counts', models.IntegerField(default=1)),
                ('check_in_time', models.DateTimeField(blank=True)),
                ('check_out_time', models.DateTimeField(blank=True)),
                ('is_check_out', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adl借阅',
                'verbose_name_plural': 'Adl借阅',
                'db_table': 'Adl_borrow',
            },
        ),
        migrations.CreateModel(
            name='Adl_glossy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '光泽度',
                'verbose_name_plural': '光泽度',
                'db_table': 'Glossy',
            },
        ),
        migrations.CreateModel(
            name='Adl_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('struct_code', models.CharField(max_length=100)),
                ('adl_standard', models.CharField(default='0', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('adl_refresh', models.IntegerField(default=0)),
                ('adl_reject', models.BooleanField(default=False)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='category')),
                ('due_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Adl色板',
                'verbose_name_plural': 'Adl色板',
                'db_table': 'Adl_item',
            },
        ),
        migrations.CreateModel(
            name='Adl_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Adl_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ADL种类',
                'verbose_name_plural': 'ADL种类',
                'db_table': 'Adl_type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('eng_name', models.CharField(default='未命名', max_length=50, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='category')),
                ('site_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'db_table': '类别',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('eng_name', models.CharField(default='未命名', max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='category')),
                ('site_url', models.URLField(blank=True)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('Modtime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'db_table': '项目列表',
                'ordering': ('Createtime',),
            },
        ),
        migrations.AddField(
            model_name='adl_item',
            name='adl_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Adl_region'),
        ),
        migrations.AddField(
            model_name='adl_item',
            name='adl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Adl_type'),
        ),
        migrations.AddField(
            model_name='adl_item',
            name='glossy_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Adl_glossy'),
        ),
    ]
