# Generated by Django 2.1 on 2018-08-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='未命名', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='eng_name',
            field=models.CharField(default='未命名', max_length=100, unique=True),
        ),
    ]
