# Generated by Django 2.1 on 2018-08-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180815_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
