# Generated by Django 2.0.7 on 2018-11-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180815_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adl_glossy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '光泽度',
                'verbose_name_plural': '光泽度',
                'db_table': '光泽度',
            },
        ),
        migrations.CreateModel(
            name='Adl_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('adl_region', models.BooleanField(default=True)),
                ('struct_code', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Adl色板',
                'verbose_name_plural': 'Adl色板',
                'db_table': 'Adl色板',
            },
        ),
        migrations.CreateModel(
            name='Adl_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ADL种类',
                'verbose_name_plural': 'ADL种类',
                'db_table': 'ADL种类',
            },
        ),
        migrations.AddField(
            model_name='adl_item',
            name='adl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Adl_type'),
        ),
        migrations.AddField(
            model_name='adl_item',
            name='glossy_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Adl_glossy'),
        ),
    ]
