# Generated by Django 2.0.7 on 2018-11-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181110_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='adl_item',
            name='picture',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
    ]
