# Generated by Django 2.0.7 on 2018-11-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_adl_item_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adl_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '区域',
                'verbose_name': '区域',
                'db_table': '区域',
            },
        ),
        migrations.RenameField(
            model_name='adl_item',
            old_name='Createtime',
            new_name='createtime',
        ),
        migrations.AlterField(
            model_name='adl_item',
            name='adl_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Adl_region'),
        ),
    ]
