# Generated by Django 2.0.7 on 2018-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181110_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='adl_item',
            name='adl_standard',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
