# Generated by Django 2.0.7 on 2018-11-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_adl_item_adl_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adl_item',
            name='picture',
            field=models.ImageField(upload_to='category'),
        ),
    ]
