# Generated by Django 2.1 on 2018-08-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品类别表', 'verbose_name_plural': '商品类别表'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('Createtime',), 'verbose_name': '商品列表', 'verbose_name_plural': '商品列表'},
        ),
    ]
